### ISSUE TITLE
Yukon Android Bug: Dropping Card Stack Doesn't Drop

### ISSUE THREAD

**Issue by AntumDeluge** [shlomif/PySolFC#114]
Sometimes while playing Yukon on my Android device, I will move a stack of cards but they will freeze instead of drop onto the target stack. I have to tap the frozen cards to get them to return to the source stack. I am not sure if other games are affected.

I have [uploaded a video to demonstrate](https://youtu.be/lGK_U63t3ws).

My system:
- Motorola Moto G4 Play
- Android 7.1 (Lineage os 15.1)

**Comment by shlomif** [comment]
Thanks for the report. @lufebe16 : any idea?

**Comment by lufebe16** [comment]
Thanks for the report.

The error described here is easily reproducible and does not depend on the operating system version. A workaround is simple: The blocked animation is reactivated by a new drag. The games and their correct course is not endangered by this.

The problem is probably based on a conflict of old software parts (drag) and new ones (animation). I usually don't use the drag-and-drop mode myself but use point-and-click (see: options->touchmode).
