### ISSUE TITLE
[BUG] Cannot start the game

### ISSUE THREAD

**Issue by reynum2** [shlomif/PySolFC#127]
HI,

When I try to start pysolfc I have this message.

```bash
pysolfc 
pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/usr/games/pysolfc", line 32, in <module>
    sys.exit(main(sys.argv))
  File "/usr/share/games/pysolfc/pysollib/main.py", line 359, in main
    r = pysol_init(app, args)
  File "/usr/share/games/pysolfc/pysollib/main.py", line 339, in pysol_init
    if not app.loadCardset(cardset, progress=progress, update=1):
  File "/usr/share/games/pysolfc/pysollib/app.py", line 872, in loadCardset
    images = Images(self.dataloader, cs)
  File "/usr/share/games/pysolfc/pysollib/images.py", line 60, in __init__
    if TOOLKIT == 'tk' and Image and Image.VERSION >= '1.1.7':
AttributeError: 'module' object has no attribute 'VERSION'
```

I use Linux Debian 10.
my python is "Python 2.7.16+ (default, Jul  8 2019, 09:45:29) "

**Comment by shlomif** [comment]
pysolfc starts fine in my debian 10 virtualbox VM after I `apt install`ed it. Note however that it is out of date there - version 2.0. Regarding your issue - you may have a https://en.wikipedia.org/wiki/Python_Package_Index package causing problems.

**Comment by scottfurry** [comment]
There's old code being used here. Gentoo had a patch file that removed the line being complained about. Doing an update/test building and found the reference. Double checked in github sources to find the line was removed already. If debian is tripping over this, they're not using up to date.

**Comment by jnumm** [comment]
Hi.

I'm involved in pysolfc Debian maintenance since a couple weeks.

It seemed that the posted error message was related to upgrade of Pillow from version 5 to 6. Pysolfc was recently upgraded to 2.6.4 in Debian Unstable, and then Testing (ie. Debian 11) will follow in five days. Because Debian 10 has Pillow 5, I suspect you may something nonstandard installed.

Please use Debian's `reportbug` program to gather additional package version information and either post it here, or submit a bug report to Debian.

**Comment by reynum2** [comment]
It ok I have force the 2.6.4 (the previous was the 2.0) version and it works again
