### ISSUE TITLE
Only shortcuts with modifiers work on Windows

### ISSUE THREAD

**Issue by FreeFull** [shlomif/PySolFC#141]
On Windows, shortcuts such as `a` for autodrop or `p` for pause don't work. Shortcuts that use `Ctrl` do work. It seems that holding `Ctrl` is also enough to make the shortcuts that don't need it work (so `Ctrl+a` does autodrop) if there isn't a conflicting `Ctrl` shortcut.

**Comment by d-mal** [comment]
I was wondering about those keyboard shortcuts, too, because they don't work on my Windows 10 x64. 
There is an explanation: https://sourceforge.net/p/pysolfc/discussion/503709/thread/3811f1a0/

It seems the code has a bug that means you need to turn off all the "locks" (NumLock, CapsLock, ScrollLock) in order for the single-key shortcuts to work on Windows. Maybe this is something that could be fixed in the future.

**Comment by jnumm** [comment]
Hi all,

Thanks for reportinh this. If you want to try out a version that should fix this keyboard shortcut issue, please try out the .exe at https://ci.appveyor.com/project/shlomif/pysolfc/builds/39917782/artifacts.

**Comment by joeraz** [comment]
Tested this fix, and it was released in version 2.12.0.  Closing the ticket.

Please reopen if this continued to be an issue.
