### ISSUE TITLE
Python 3.8 variable change 

### ISSUE THREAD

**Issue by mlmatlock** [shlomif/PySolFC#145]
Arch updated to Python 3.8.  Starting pysol 2.6.4 after upgrade:
`
Traceback (most recent call last):
  File "/usr/bin/pysol", line 36, in <module>
    from pysollib.main import main  # noqa: E402,I202
  File "/usr/lib/python3.8/site-packages/pysollib/main.py", line 30, in <module>
    from pysollib.app import Application
  File "/usr/lib/python3.8/site-packages/pysollib/app.py", line 31, in <module>
    from pysollib.gamedb import GAME_DB, GI, loadGame
  File "/usr/lib/python3.8/site-packages/pysollib/gamedb.py", line 28, in <module>
    from pysollib.mfxutil import Struct, print_err
  File "/usr/lib/python3.8/site-packages/pysollib/mfxutil.py", line 146, in <module>
    uclock = time.clock
AttributeError: module 'time' has no attribute 'clock'
`
From Python 3.8 docs:

> The function time.clock() has been removed, after having been deprecated since Python 3.3: use time.perf_counter() or time.process_time() instead, depending on your requirements, to have well-defined behavior.

Manually changing mfxutil.py to either new variable works.

**Comment by shlomif** [comment]
On Thu, 14 Nov 2019 18:36:18 -0800
mlmatlock <notifications@github.com> wrote:

> Arch updated to Python 3.8.  Starting pysol 2.6.4 after upgrade:
> `
> Traceback (most recent call last):
>   File "/usr/bin/pysol", line 36, in <module>
>     from pysollib.main import main  # noqa: E402,I202
>   File "/usr/lib/python3.8/site-packages/pysollib/main.py", line 30, in
> <module> from pysollib.app import Application
>   File "/usr/lib/python3.8/site-packages/pysollib/app.py", line 31, in
> <module> from pysollib.gamedb import GAME_DB, GI, loadGame
>   File "/usr/lib/python3.8/site-packages/pysollib/gamedb.py", line 28, in
> <module> from pysollib.mfxutil import Struct, print_err
>   File "/usr/lib/python3.8/site-packages/pysollib/mfxutil.py", line 146, in
> <module> uclock = time.clock
> AttributeError: module 'time' has no attribute 'clock'
> `
> From Python 3.8 docs:
> 
> > The function time.clock() has been removed, after having been deprecated
> > since Python 3.3: use time.perf_counter() or time.process_time() instead,
> > depending on your requirements, to have well-defined behavior.  
> 
> Manually changing mfxutil.py to either new variable works.

This was fixed in git master, and arch linux should use a downstream patch. It
sucks that python keeps breaking back compat but it could be much worse:

https://www.shlomifish.org/humour/fortunes/show.cgi?id=compiling-a-C-program-from-20-years-ago

> 
> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/lecture/C-and-CPP/bad-elements/

Knuth is not God! Unless you confuse him with Dijkstra.
    — http://www.shlomifish.org/humour/bits/facts/Knuth/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by jnumm** [comment]
Let's close this issue because it is fixed in git master.
