### ISSUE TITLE
Italian/neapolitan cards game

### ISSUE THREAD

**Issue by TeoColuccio** [shlomif/PySolFC#156]
Is there same classic Italian cards game with Neapolitan cards, like "scopa" or "briskola"?

**Comment by shlomif** [comment]
@TeoColuccio : hi! For everyone who reads this one should note that this question was also posted here:

* https://groups.google.com/forum/#!topic/foss-card-games/PtoZdSMjpyU

* https://sourceforge.net/p/pysolfc/discussion/503708/thread/eda781b1a3/?limit=25#c12f

Please have more patience.

My reply is the same: you may either find an existing implementation (using a https://en.wikipedia.org/wiki/Web_search_engine ) or alternatively implement it yourself while possibly utilising some [FOSS](https://en.wikipedia.org/wiki/Free_and_open-source_software) code and art, while abiding by their licences.

Otherwise, note that the gods help them that help themselves /etc. and implementing these games is not a priority for me.

Closing this issue,
