### ISSUE TITLE
Simple Simon solver bug

### ISSUE THREAD

**Issue by Arcorann** [shlomif/PySolFC#168]
I notice that when the solver is run in Simple Simon it frequently fails to find a solution even when a solution exists. An example is this saved state from Simple Simon game 98804262199142645760, where the solver fails to find a solution. If the the 7 and 6 of diamonds are moved to an empty column the solver succeeds in finding a solution.

[Simple Simon-98804262199142645760_solverfail.zip](https://github.com/shlomif/PySolFC/files/4943373/Simple.Simon-98804262199142645760_solverfail.zip)

**Comment by shlomif** [comment]
@Arcorann : hi! See [this answer](https://fc-solve.shlomifish.org/faq.html#unsolvable_solution). The Simple Simon solver uses meta-moves which may lower its accuracy. I recall that using atomic moves (= a single hegemonous sequence at a time) made it too time&RAM consuming at the time but there may different approaches.

**Comment by Arcorann** [comment]
Thanks for the link. Looking at [the usage page](https://fc-solve.shlomifish.org/docs/distro/USAGE.html) I see that there are a number of presets (many of which are only describe as "a meta-moves preset"). Having tested all the presets, I find that all of them except video-editing solve the game that I posted given its starting state. Is there any particular reason why video-editing is the default?

**Comment by shlomif** [comment]
> Thanks for the link. Looking at [the usage page](https://fc-solve.shlomifish.org/docs/distro/USAGE.html) I see that there are a number of presets (many of which are only describe as "a meta-moves preset"). Having tested all the presets, I find that all of them except video-editing solve the game that I posted given its starting state. Testing on other games (such as Baker's Dozen) I also notice that many of the other presets seem much faster than video-editing. Is there any particular reason why video-editing is the default?

Hi @Arcorann ! Since loading other people's saved games is insecure due to the use of [pickle](https://docs.python.org/3/library/pickle.html) can you please provide a "File -> Export current layout" output (and maybe a screenshot as well)? Also provide details of your OS and how you installed pysol.

Regarding the presets: I presume most of them won't work on Simple Simon as they only work on Freecell-like games. "video-editing" was selected as the default because it tends to yield shorter solutions (at least on Freecell with 4 reserves).

**Comment by shlomif** [comment]
Closing this issue due to a lack of reply. @Arcorann : I can reopen it again once you provide more info.
