### ISSUE TITLE
[Bug] missing backs lead to error

### ISSUE THREAD

**Issue by cardset** [shlomif/PySolFC#185]
If config.txt refers to Backs in the last line,
and they don't exist, the following error appears in
pysol.log. after closing the game.

NoneType object has no attribute subsample

**Comment by jnumm** [comment]
Hi @cardset, thanks for reporting this. I was able to make PySolFC print a more specific diagnostic message for this case; commit 0be465dea1932a0977fb8a0bb023f18431a354a3. Do you think that is adequate?

**Comment by cardset** [comment]
That sounds good.

But the real issue is. The cardset can't load
because of an additional backcard. 
But the game needs only one single backcard to work.

**Comment by jnumm** [comment]
If I understand correctly, that's fixed already.

Let's say I have modified cardset-dondorf/config.txt
```PySolFC solitaire cardset;4;.gif;1;52;7
123-dondorf;Dondorf
79 123 8
16 25 7 7
back01.gif
back01.gif;back00.gif
```
Note that the additional back `back00.gif` does not exist. Now when PySolFC goes to load that cardset, this will be printed:

    PySolFC: WARNING: card image path /home/juhani/.PySolFC/cardsets/cardset-dondorf/back00.gif does not exist
    PySolFC: WARNING: in /home/juhani/.PySolFC/cardsets/cardset-dondorf/config.txt: card back "back00.gif" does not exist

but because there is a single working card back `back01.gif`, the cardset works.

**Comment by cardset** [comment]
Works fine now. Thank you
