### ISSUE TITLE
Crash: 'bool' object has no attribute 'items'

### ISSUE THREAD

**Issue by jnumm** [shlomif/PySolFC#193]
There is an [error report in the sf.net forum](https://sourceforge.net/p/pysolfc/discussion/503708/thread/aa31f6d2cd), `'bool' object has no attribute 'items'`. I am not certain which conditions will trigger the problem.

We possibly need to fix https://github.com/shlomif/PySolFC/blob/master/pysollib/options.py#L651 as the return value of configobj validation may be True, False or a dict. [Configobj documentation](https://configobj.readthedocs.io/en/latest/configobj.html#simpleval) has an example of that.

Below: picture from arctic-cat, https://sourceforge.net/p/pysolfc/discussion/503708/thread/aa31f6d2cd
![Pic from arctic-cat](https://user-images.githubusercontent.com/1366407/98295453-45c74f00-1fba-11eb-8d53-b1521475b8a9.png)

**Comment by jnumm** [comment]
To get such an error, I cleared the options file, i.e. `echo ''> ~/.PySolFC/options.cfg` on linux. I will push a fix to master.

**Comment by shlomif** [comment]
On Fri, 06 Nov 2020 08:37:55 -0800
Juhani Numminen <notifications@github.com> wrote:

> To get such an error, I cleared the options file, i.e. `echo ''>
> ~/.PySolFC/options.cfg` on linux. I will push a fix to master.
> 

Thanks!

-- 

Shlomi Fish       https://www.shlomifish.org/
https://is.gd/htwEXQ - Integrating GNU Guile into GNU coreutils

Chuck Norris was never a newbie! He will kill anyone who implies otherwise. In
a very not newbie-like manner.
    — https://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - https://shlom.in/reply .
