### ISSUE TITLE
Github workflow, discussions, issues

### ISSUE THREAD

**Issue by hairspring** [shlomif/PySolFC#20]
I have no previous experience of Github, I'm hoping some here in Github/PySolFC have participated in other shared projects on Github and can advise what works.

My impression is that our need for discussion is cluttering issues, leading us off-topic.  In a few years (months?) time that will make it hard to review an issue.  E.g. on Ubuntu's Launchpad often a bug is reported and if it isn't fixed quickly then there can be 50 or 100 follow-ups, arguments, irrelevancies, etc.  Developers have little spare time, and such bugs are just left to rot, the extensive trail discourages devs.  So we should aim to keep our issues focussed.

I would imagine a PySolFC mailing list would be a good way to avoid some of this clutter.  Github doesn't seem to have mailing lists for projects.  Might the wiki be a solution?

**Comment by jan-kleks** [comment]
I've suggested a mailing list to shlomif, but he does not seem to like that idea.

**Comment by hairspring** [comment]
If Github provided one, I'd like that.  But since it doesn't, I feel shlomif is right, for it would be a lot of work for someone to create and support one, and we'd never know if it would vanish at some point.  So we have to work with the tools we have.

Well, at least this issue #20 can serve as a discussion about that, without cluttering others! :)

Thanks, Jan.

**Comment by jan-kleks** [comment]
@hairspring I think you can now close this topic, I've changed the name of my topic (https://github.com/shlomif/PySolFC/issues/17) so that it would encompass more things.

**Comment by jan-kleks** [comment]
@hairspring Ups, I didn't notice that you want to actually use this issue for discussion... Sorry. Nevermind, the most important thing is that shlomif would realize that we need topics created specifically for discussion.

**Comment by shlomif** [comment]
On Tue, 18 Apr 2017 04:12:25 -0700
Jan Kleks <notifications@github.com> wrote:

> I've suggested a mailing list to shlomif, but he does not seem to like that
> idea.
> 

I'm now quite supportive of the idea of setting up a mailing list or a similar
forum for PySol because it seems there's enough interest. We can get one at
Google Groups, Yahoo Groups, etc. I suppose a reddit subreddit is also an
option.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
List of Portability Libraries - http://shlom.in/port-libs

Java is a DSL (= Domain Specific Language) to transform big XML documents
into long exception stack traces. — Scott Bellware

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by hairspring** [comment]
> I didn't notice that you want to actually use this issue for discussion..
@jan-kleks No problem.
> I think you can now close this topic
I agree.  Merging to #17 and closing this one.
