### ISSUE TITLE
Find card option -- switch for "stay on top" (but only when Pysol is the active application)

### ISSUE THREAD

**Issue by jan-kleks** [shlomif/PySolFC#25]
Switch for "stay on top" (but only when Pysol is the active application).

As suggested by Hans-Joachim Gurt at SF.net

**Comment by joeraz** [comment]
Main issue with this is that the logic that controls which window is on top comes from the Operating System rather than Python/Tkinter.  I did some initial research, and while it sounds like Tkinter can be manipulated to do this, it would have to be done on an OS by OS basis, and I can only test on Windows and Debian personally.

**Comment by joeraz** [comment]
I was able to figure out how the topmost attribute can be used to do this.  I set this up for the find card dialog, with an option to enable/disable it.
