### ISSUE TITLE
Crash on Run

### ISSUE THREAD

**Issue by p-bea** [shlomif/PySolFC#251]
Good Day . . .

I just installed Kubuntu 22.04 and I installed PySolFC and PySolFC-cardsets. The download from the Kubuntu repositories was unremarkable.

When I ran the program the following showed up. I have absolutely no idea whether this is a PySolFC or Kubuntu 22.04 issue. I must start some place.

Can anyone give me some idea on who may want ownership of this issue. If the issue is one of 'update to the latest version' then I have never built programs myself. I must admit that I am a little out of my depth. I had to open this account which I wasn't really in favour of creating.

Can anyone point me in the direction to resolve this issue?

"Traceback (most recent call last):
  File "/usr/games/pysolfc", line 36, in <module>
    from pysollib.main import main  # noqa: E402,I202
  File "/usr/share/games/pysolfc/pysollib/main.py", line 30, in <module>
    from pysollib.app import Application
  File "/usr/share/games/pysolfc/pysollib/app.py", line 32, in <module>
    from pysollib.images import Images, SubsampledImages
  File "/usr/share/games/pysolfc/pysollib/images.py", line 28, in <module>
    from pysollib.pysoltk import copyImage, createBottom, createImage, loadImage
  File "/usr/share/games/pysolfc/pysollib/pysoltk.py", line 35, in <module>
    from pysollib.tile.tkhtml import *  # noqa: F401,F403
  File "/usr/share/games/pysolfc/pysollib/tile/tkhtml.py", line 29, in <module>
    from pysollib.ui.tktile.tkhtml import Base_HTMLViewer
  File "/usr/share/games/pysolfc/pysollib/ui/tktile/tkhtml.py", line 24, in <module>
    import formatter
ModuleNotFoundError: No module named 'formatter' "

After receiving the above I thought it may be a dependency issue so I downloaded all the dependencies and all the recommended but still no joy.

Thank You Ladies and Gentleman I really appreciate your work.

p-bea

**Comment by joeraz** [comment]
I am familiar with this error.  This happens if you are using Python 3.10 with a version of PySolFC prior to 2.14.  The "formatter" it speaks of is a component of Python itself that was removed in 3.10.  We've since updated PySolFC to account for its absence, but pre-2.14 versions of PySolFC will not work with Python 3.10.

I'd recommend either upgrading PySolFC to 2.14 or later, or downgrading Python to 3.9 or earlier.  If you're retrieving the packages through apt-get install, I'd suggest contacting whomever maintains your Linux distribution and request that they upgrade the PySolFC packages.  Or I can give you instructions on how to run the latest version of PySolFC from the source code if you wish.

**Comment by p-bea** [comment]
Thank You for the quick reply. It is appreciated.

I thought that something like this was causing the issue. I realise that you are probably busy so I tried to make the executable and failed miserably. My progress ended when the file 'install-pysol'* was not found in 'scripts'.

That said I am willing to try again because I have been using this program and its' previous iteration for about 15 - 20 years. It seems to be the only card games that I win (sometimes).

If you can point me into the direction of the easiest instructions for creating the executable I would really appreciate it.

Keep up the good work.

p-bea

**Comment by p-bea** [comment]
I hope that this gets to you before you expend any energy on this issue.

The issue is resolved! Not as you would expect but something entirely different.

I was having so many problems with Kubuntu 22.04. PySolFC wouldn't run. My UPS lost communications with the computer. Executables wouldn't run in Dolphin. The desktop refresh had problems. So I restored a CloneZilla device backup of 20.04 and now I am running just fine. The computer is talking to the UPS. Desktop refresh works well. Executables run in Dolphin and above all I have a working copy of PySolFC, an older copy but still a working copy.

I will need to upgrade sooner or later but when the time comes I hope that the Ubuntu repositories are updated.

Again I Thank You for your interest. Keep up the good work.

p-bea

**Comment by joeraz** [comment]
Understood, thanks.

Unfortunately, the Linux builds can vary from environment to environment, so it's difficult to provide build instructions.  Whereas, we have automated jobs that can create Windows or Mac installers as needed.  I think most Linux installs mostly run pysol.py with Python directly, but I'll see if I can figure out more of those details for future reference.

Nonetheless, since you've resolved your issue, I'll close this.
