### ISSUE TITLE
Version 2.15 (Windows) - Select Random Game (Ctrl-R) only ever selects games of the same type currently being played 

### ISSUE THREAD

**Issue by UncreativeHub** [shlomif/PySolFC#254]
If I start a new game of random type (either using 'ctrl-r' or 'File->Select Random Game->All Games'.) Pysol will only pick games of the same type (ie. from the same sub menu in the 'Select' menu)

eg. If I am playing a Hanafuda game, select random game will only ever pick another Hanafuda game.

**Comment by joeraz** [comment]
Looked at the code, this appears to be intentional.  Not sure why it was done this way, as the logic was in place long before I got involved in the project.  I speculate that this might be due to the possible need to load new cardsets when changing the game category.

I'd have to do a little more research on the code to see if there's a way I can implement this as an option.

**Comment by joeraz** [comment]
Upon closer review, I can't think of a good reason for this category restriction logic to be in place.  Even the all games demo can randomly choose games that use different cardset types.

I went ahead and removed the logic, but will revisit if I find this leads to further issues later.
