### ISSUE TITLE
"Confirm quit" option does not work

### ISSUE THREAD

**Issue by VedVid** [shlomif/PySolFC#270]
Option "Confirm quit" does not work for me. 
No matter if the option is checked or not, the program quits immediately after pressing the "X" button.

Version: 2.16.0
OS: Windows 10 x64

**Comment by joeraz** [comment]
The confirmation dialog only shows if you attempt to quit in the middle of the game (after you've already made at least one move and haven't used undo to go back to the beginning).  I just tested and confirmed this.

Can you confirm when you're attempting to quit when you don't get the confirmation?

**Comment by VedVid** [comment]
I confirm that the confirmation dialog shows when I try to quit the app in the middle of the game.

I did not expect that appearing of popup depends on the game status.

**Comment by joeraz** [comment]
It's because the main purpose of that option is to warn people if they're trying to quit mid-game, in case they wanted to save or hold the game to finish in a later session, and because quitting mid-game counts as a loss for the statistics.  Quitting an unstarted or completed game doesn't have this issue.

Though if you'd like, it shouldn't be terribly difficult to add a separate option to always confirm?

**Comment by VedVid** [comment]
I don't think it is necessary. Instead, maybe it is worth to consider change of wording? For example, from "Confirm quit" to something akin to "Confirm discarding game". It would emphasize that the option is about the solitaire-in-progress and not about the program as a whole.

**Comment by joeraz** [comment]
Done.
