### ISSUE TITLE
Cardset picker window resizes itself to cross monitor boundaries

### ISSUE THREAD

**Issue by ssokolow** [shlomif/PySolFC#273]
At some point since the 2.6.4 release from my distro package manager, PySolFC started resizing the cardset picker window to fill most of the screen.

Undesirability of that behaviour aside, it reacts badly to multi-monitor desktops, as demonstrated by this screenshot. (I've drawn 2px borders to show where the boundaries of my three monitors are.)

![pysolfc_bug_screenshot](https://user-images.githubusercontent.com/46915/189734301-8c3638cd-91ca-446f-9886-c027abb9600e.png)

I've confirmed this behaviour to exist in the current git HEAD (7f0c6e18ec6eae494feb5229f12dbf26510071b6) and the 2.16.0 release that gets built by the Flatpak manifest I'm putting together as the newest tagged release.

A `git bisect` traces the problem down to commit 513962b8f3924db6b3eb0bb5b942d59f0a563981, when it went from filling one monitor to 100% width to filling maybe 80% of a three-monitor desktop.

(I'm still not a fan of having a tiny PySolFC window spawn a cardset picker with card previews much bigger than in actual play... or, for that matter, much bigger than the rest of the widgets in the window, but that's another matter.)

**Comment by ssokolow** [comment]
If you only have one monitor and need to test for this behaviour, you can use Xephyr with a command like this:

```sh
Xephyr -screen 640x480 -screen 640x480 -screen 640x480 +xinerama :1 &
sleep 1
DISPLAY=:1 python3 pysol.py
```

![pysolfc_bug__Xephyr_screenshot](https://user-images.githubusercontent.com/46915/189738656-8b8d6e3e-fb81-4c15-94bd-af859c818956.png)


...though you may also want to stick something like `DISPLAY=:1 openbox` in there to verify it's playing nice with a window manager.

**Comment by ssokolow** [comment]
It also doesn't handle unusual monitor layouts well, as demonstrated by 

```sh
Xephyr -screen 640x480 -origin 640,0 -screen 640x480 -origin 0,480 -screen 640x480 +xinerama +extension RANDR :1 &
sleep 1; 
DISPLAY=:1 python3 pysol.py
```

![pysolfc_bug__Xephyr_2_screenshot](https://user-images.githubusercontent.com/46915/189740375-e15548c8-0c6e-4814-a46a-46616cffdb3f.png)

**Comment by joeraz** [comment]
I do have a two monitor system, and am not experiencing this issue.  I'll look into this - the window may need to scale to the main window rather than the user's screen.

The main reason this was done is because of the large size of the previews used by high resolution cardsets both here and in the select game window.  The reason the cardset shows so large in the preview window is because that is its original size, whereas auto-scaling resizes the cards to the size that best fits the screen.  If you disable auto-scaling, you'll notice the cards in the game are just as large as they show in the preview.  I've tried to apply auto-scaling to the previews, but it didn't work as well as I'd hoped.  The window needs to be big enough to show the preview without forcing the user to scroll, but can't be bigger than the user's screen.

**Comment by ssokolow** [comment]
I just realized that the auto scaling checkbox is having no effect. I have to uncheck it and manually lower the scale or I just get giant cards with scrollbars.

**Comment by joeraz** [comment]
Can you let me know if the version in this branch is still having the issue: https://github.com/joeraz/PySolFC/tree/feature/scale-to-window

**Comment by ssokolow** [comment]
I'm just about to go to bed and I'll be AFK most of tomorrow, but I'll get back to you when I can spare a moment.

**Comment by ssokolow** [comment]
Yep. That works. It makes the "auto-scaling checkbox has no effect" bug I mentioned even more obvious, but it works.

Here's the size it now shows up as on my desktop, which is clearly calculated as something like "80% of the playfield window, bottom-center aligned". (I have PySolFC's main window small for test purposes right now.)

![Screenshot_20220916_194027](https://user-images.githubusercontent.com/46915/190831148-b103c884-b169-40b9-9b50-775fdb1f7c26.png)

Sorry for the delay. The dentist said that the tendency toward sensitivity I'd been feeling in one tooth had finally developed into a cavity big enough for him to find, so I had to go in a second day in a row to get it fixed.

**Comment by joeraz** [comment]
No problem.  Merged that to master.

Yeah, that's the current formula - I try to align it as close to the center as possible, but the window has a minimum size of about 400x200 (as it's pretty much unusable if it's any smaller), so it may get shifted to the bottom-right on really small windows.

Auto-scaling in the preview windows was actually one of the first things I tried to implement.  Unfortunately, when I did add it, it caused the game to freeze frequently.  There's a bug where if the contents of the preview windows are sized too closely to the canvas, the canvas will be unsure whether to display scrollbars, and get caught in an endless loop between showing and hiding the scrollbars.  Currently, it's an extremely rare issue that only occurs for very specific combinations of cardsets, window sizes, games, and previously selected cardsets/games (I'm only aware of it because I've played around with the scaling logic and hi-res graphics extensively).  But when I tried to add auto-scaling to previews, it regularly froze up the app.  Unless this bug is fixed, implementing auto-scaling in the previews would not be practical.

**Comment by ssokolow** [comment]
So the same bug that web development had for ages before they started switching to overlay scrollbars.

I'm not familiar with Tkinter. Is there no way to either lock the scrollbars on, even if they don't do anything, or lock them off and implement PDF-esque grabbing-hand-cursor scrolling?

**Comment by joeraz** [comment]
I tried locking them off when auto-scaling was enabled, but it didn't handle the toggle too well.  Hand scrolling would cause issues with the game previews.  I did a bit of research on the tkinter side, but there's also some custom canvas code done by the previous developers.

Either way, because the main issue is resolved, I'll close this ticket.  I'll set up another ticket for this later if I don't figure it out for the 2.18 release.
