### ISSUE TITLE
id-numbers for games and cardsets

### ISSUE THREAD

**Issue by hajo4** [shlomif/PySolFC#290]
I understand that each game has a unique id-number.

If I want to create a new game/variant for pysol, how do i get such an id ?
Are some numbers already reserved ?

Same question for cardsets - who assigns names / ids ?

**Comment by joeraz** [comment]
There isn't really a formal system in place.  Right now, I'm the one adding most of the new games, and I just use the lowest available numbers (which is currently the upper 800s).  I can reserve an ID temporarily to avoid conflicts, but only until the next release, for organization reasons.  Though I'd suggest just finding the next usable ID and just using it (check the dev version in GAMES_BY_PYSOL_VERSION in gamedb.py to see the ID range I'm currently using) - and if there's a conflict, update before you merge the code.

There are a few protected IDs.  These are used for games that either had their IDs changed or were removed.  Using these IDs will cause PySol to crash - they are listed in the PROTECTED_GAMES object in gamedb.py.  Additionally, IDs in the 200,000s are reserved for Solitaire Wizard created games.

Also, some of the special deck games have their own separate ID ranges, if you're making one of those, check other games of the same type.

As for cardset IDs, once again, no formal system in place.  Cardset IDs are full strings rather than just numbers, so if you include some variation of the cardset name in the ID, there's very little risk of accidentally making a duplicate (and if you do, just adjust the number).

Does that answer your question?

**Comment by hajo4** [comment]
Thanks !

I was thinking about a game based on the Pancake-sorting problem 
(would be somewhat like Tower-of-Hanoi),
or maybe a simple game such as Nim.

With cardsets for Memory, it would be nice to have sets with themed pictures,
eg. flowers, birds, etc. (maybe even without the cardsymbols).
With those, I don't see how the config for the cardset needs to be set up
so pysol allows them to used with memory-type games.

**Comment by joeraz** [comment]
Whether a game supports a cardset is based on the game's category, the cardset type, and the number of cards.  For the most part, games can only use cardsets of the same type that have the required number of cards.  Though there are a few special rules - Mughal Ganjifa games can use Dashavatara Ganjifa decks, for example.

But creating a separate Matching type deck might be the solution to issue #289 - I'd have to try that out and see how well that might work.
