### ISSUE TITLE
Help / Demo, Solver

### ISSUE THREAD

**Issue by hajo4** [shlomif/PySolFC#293]
The help has no entries about Demo and the solver.

Ie. what is the difference between "Demo" and "Demo (all games)" ?
Because when started with eg. freecell selected, 
"Demo (all games)" doesn't change to other games.

(Also, it would be nice to be able to specify when to stop,
 eg. after a won game, or after a certain number of games)

And what do the solver-presets mean ?

(Also, an option would be nice to run the solver automatically
 on each new game, to get "solvable games only")

**Comment by joeraz** [comment]
I can add a section to the Assist Options page about the demo - basically, when the demo is completed and you get the autopilot notice indicating whether it won or lost, if you ignore the message box a few seconds, it will go away on its own and start another game.  If you selected "Demo", it'll just start another round of the current game, if you selected "Demo (all games)", it will randomly choose another demoable game of the same category and start that.  If you keep ignoring that message box and don't interrupt it, it'll go on forever.

@shlomif - Do you have a page of documentation for the Solver somewhere that I can add to the PySolFC help?

**Comment by shlomif** [comment]
On Mon, 30 Jan 2023 14:43:33 -0800
"Joe R." ***@***.***> wrote:

> I can add a section to the Assist Options page about the demo - basically,
> when the demo is completed and you get the autopilot notice indicating
> whether it won or lost, if you ignore the message box a few seconds, it will
> go away on its own and start another game.  If you selected "Demo", it'll
> just start another round of the current game, if you selected "Demo (all
> games)", it will randomly choose another demoable game of the same category
> and start that.  If you keep ignoring that message box and don't interrupt
> it, it'll go on forever.
> 
> @shlomif - Do you have a page of documentation for the Solver somewhere that
> I can add to the PySolFC help?
> 

for fc-solve:

* https://fc-solve.shlomifish.org/docs/

* https://fc-solve.shlomifish.org/faq.html

for black-hole-solve:

* https://github.com/shlomif/black-hole-solitaire

-- 

Shlomi Fish       https://www.shlomifish.org/
My Photos - https://www.flickr.com/photos/shlomif/

One of my most productive days was throwing away 1,000 lines of code.
    — Ken Thompson (Attributed)

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by joeraz** [comment]
Lots of info here, but I should be able to write a summary for PySolFC users with that, and provide links to the full docs.  Thanks.

**Comment by joeraz** [comment]
Okay, got a basic doc on how to use the solver in place, though it's pretty basic and I mostly link to the solvers' main documents for further details.

Regarding using the solver to add a "winnable games only" option, I don't think this is currently practical because the solver is an optional component, and only a few games work with the solver.  It might be possible to expand this to more games by leveraging some of the hint/demo logic, but how accurate it would be depends on the game.  I can think of quite a few issues we'd need to work through to implement something like that - if you want to discuss further, please open a separate issue for that, and I can elaborate on my concerns there.  This topic probably deserves its own discussion thread.
