### ISSUE TITLE
Will Jokers ever be in this game?

### ISSUE THREAD

**Issue by LinuxBeaver** [shlomif/PySolFC#298]
In classic patience games Jokers usually serve as Wild Cards. None exist in Pysol. Is this planned?

**Comment by joeraz** [comment]
Yes, this is on my to-do list.  However, because this will involve some required changes to the cardsets package, I consider this a 3.0 feature.

The main issue right now is the fact that most of the current cardsets do not contain the joker images (a few contain joker cards, but no way to use them).  I've already done some looking for the original sources for several of the cardsets and have been able to track down a number of the joker card images.  But there are still a lot of cardsets that I haven't been able to track down the original sources or the joker cards for.

Current plan is for it to be optional for a french cardset to include jokers, but you won't be able to play joker deck games with cardsets that don't have them.

**Comment by LinuxBeaver** [comment]
cool - thanks for letting me know.
