### ISSUE TITLE
Android 12 - App keeps closing

### ISSUE THREAD

**Issue by BaijinBullet** [shlomif/PySolFC#299]
TL;DR:  after update to 2.18.0 on Android 12 app cannot start, immediately goes black;  deleted cache, data, tried uninstall/reinstall, no success.  Thank you for your time! 

I recently updated from an old version (do not know which) to the version 2.18.0.  
I think my last update cycle was half a year ago, so probably a version from back then.
Things I tried:
- stop app + delete cache
- stop app + delete cache + move and rename .PySolFC folder
- the above + delete data
- uninstall, reinstall
- uninstall, restart phone, reinstall

Open to any reasonable suggestions.  Thank you kindly!

**Comment by joeraz** [comment]
Not really an expert in the Android version, but I know it's been a while since the last Android package was pushed (like 2.10 or older).  I'm planning a release package later today anyway, so I'll see if I can get a new Android package with it.

**Comment by BaijinBullet** [comment]
New version 2.20 works!  It seems it stores its data in a different location, so it does not pickup old statistics.dat, but that is not big issue.  Thank you, best card game app!

**Comment by joeraz** [comment]
Great!  Thanks for confirming.

**Comment by lufebe16** [comment]
Thanks too for confiming. This addresses also issues #279 and #284.

The new Version 2.20 is now also available on f-droid.  Enjoy.

Remark:
PysolFC on Android Versions >= Android 10 can not store its setting in the Android external storage but stores them into the (hidden) app storage.  It so is not possible to add additional Fonts etc. This is due to new restrictions on storage access with newer Android versions.

**Comment by joeraz** [comment]
Okay, I'll go ahead and close those then.
