### ISSUE TITLE
Cardset error missing french (joker deck) on start

### ISSUE THREAD

**Issue by lufebe16** [shlomif/PySolFC#337]
I use the latest cardsets from Sourceforge (Version 2.2.0). With my development version I get a cardset error on any startup. Please update cardsets on Sourceforge.

Or find a way to disable that check per settings.

Anyway I think it is not the right way to check cardsets on programm start, except if all cards are missing. Please check if it is not possible to issue these type of errors, when a user starts a special game that needs these special cards. Not all users plan to play all games.

When updating cardsets on Sourceforge please also take an eye on not to blow the minimal cardsets as they are used with the android version and go directly into the apk.

**Comment by joeraz** [comment]
Are you looking to do a release, or do you just want that error message to go away during development?

I recently made some changes to the cardsets format - while old cardsets will work, the new format is needed to support things like Jokers, and Puzzle type cardsets of different sizes.  While the changes I made so far are finished, they're not ready for release yet.  Since the cardsets package is separate from the main code, I want to limit the number of times it gets updated, to make things easier for the Linux distributors.

The reason it's on the startup is not for the users, but for the distributors.  When I release 3.0, if the Linux distributors try to update, it being there will let them know right away that they'll need to update the cardsets package to 3.0 too.  We've previously had some bug reports because of Linux distributors not keeping their packages up to date, and I'm trying to get ahead of this one in advance.

**Comment by joeraz** [comment]
Also, the minimal package is used for some of the Windows and Mac packages too.  So it will be updated.

**Comment by lufebe16** [comment]
New release? According to my changes it would be appropriate, but it is not urgent. It can wait until all the requirements are all up to date. When do you plan to release?

**Comment by joeraz** [comment]
It's still a ways off.  I'm still doing some things with the new cardset types, and still have some other games to add.

Though if a critical enough item is resolved (such as #324), I can prepare one sooner, by branching off the last release and cherry-picking the important fixes.

In the meantime, if you want to prevent the error, you can get the latest version of the Neo cardset, plus one puzzle type set for each size from https://github.com/shlomif/PySolFC-Cardsets.  Or if you'd like, I can prepare a temporary minimal package you can use until the next release (though I still plan to add at least one more cardset type, so it may change).

**Comment by lufebe16** [comment]
Ok. It works out of the box with all cardsets from cardsets-master. For the my minimal version I finally found a list of the puzzle cardsets in pysollib/options.py to add. This works fine also with android and still does not blow up the apk size. Thanks.

**Comment by joeraz** [comment]
Yeah, with the puzzle type cardsets, I felt the pre-existing ones looked good enough on larger screens, that hi-res ones felt unnecessary.  I'll only add hi-res puzzle sets if there's sufficient demand for them (though if I do, they absolutely will blow up the file size).

The next cardset type I want to add is Ishido, which has a smaller number of cards, and a simple design, so I'm hoping that will be small too.

I do have a few ideas that might help reduce your APK size - will open another issue for that later.
