### ISSUE TITLE
Update to 3.0 resets player-options

### ISSUE THREAD

**Issue by hajo4** [shlomif/PySolFC#385]
I installed the still-current pysol 3.0 over my old 2.18,
and lost all the setting, for favorite games, cardsets, background,, sound, etc.

Most of those are no big deal,, but the list of favorite games 
is somewhat cumbersome to redo.

**Comment by joeraz** [comment]
Interesting.  Though 3.0 is a pretty major update, and some of the config formatting was changed, I tested thoroughly to make sure that the old config files were compatible.

Do you still have the old options.cfg file?  If so, could you send me a copy so I can review and test?

**Comment by hajo4** [comment]
It looks like that file was overwritten by the update ;(
I'm not sure if I can find a backup of it...

BTW, it would be nice if the update-proces would copy
the old options.cfg file to a filename like options_old.cfg

**Comment by joeraz** [comment]
There isn't really a conversion process, as the old config file is still compatible.  The new values/newly formatted values are updated as they're needed/used.

**Comment by hajo4** [comment]
I now installed the new pysol 3,1 (downloaded from sourceforge.net) over 3.0,
and again it reset the option, ie. cleared the favorites, cardset, style of toolbar, etc.

**Comment by joeraz** [comment]
Please confirm which platform you're running on (Windows, Mac, or Linux)?

**Comment by hajo4** [comment]
I'm running Win 10 currently.
I also restored a copy of the last options.cfg before the update, and it got overwritten when running pysol again.

Then I re-installed 3.0, using the existing location, and got an error:
Failed to execute script pyi_rth.pkgres due to unhandled exception:

Traceback (most recent call last):
  File "PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 158, in <module>
  File "PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 36, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pkg_resources\__init__.py", line 32, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "plistlib.py", line 70, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "xml\parsers\expat.py", line 4, in <module>
ImportError: Module use of python312.dll conflicts with this version of Python.

**Comment by joeraz** [comment]
Considering that matching type cardsets were introduced in 2.20, the older versions probably don't recognize it as a valid cardset.

Can you provide the backup options.cfg file that keeps getting overwritten?

**Comment by hajo4** [comment]
> Can you provide the backup options.cfg file that keeps getting overwritten?

 last options.cfg used on 3.0 before the update to 3.1 :
[options _30_2024-10-25.zip](https://github.com/user-attachments/files/17528500/options._30_2024-10-25.zip)

**Comment by joeraz** [comment]
It looks like the config file had a non-fatal validation warning that it should have been able to correct, and it does so if I'm running off the source code.  But the compiled version of the code is for some reason treating that non-fatal warning as a fatal error.  And since it believed there was a fatal error (as if the config was not readable at all), it just generated a new one.

I removed that warning, as there really doesn't need to be a warning there, and updated the code.  Based on my initial tests, it seems to work.  If you use an installer straight off AppVeyor (go to the latest commit, click the check box, click details next to AppVeyor, then navigate to the artifacts tab and grab that installer) to get the latest dev code, you should be able to upgrade without issue.
