### ISSUE TITLE
Implement Ctrl-Z / Control-Z for undo

### ISSUE THREAD

**Issue by aguador** [shlomif/PySolFC#71]
I basically only use PySol for Spider and have always missed not having this shortcut for undoing a move. Perhaps it cannot be implemented because of conflicts across games, but it would be a wonderful feature addition!

**Comment by shlomif** [comment]
Hi,

On Tue, 10 Apr 2018 10:37:33 +0000 (UTC)
aguador <notifications@github.com> wrote:

> I basically only use PySol for Spider and have always missed not having this
> shortcut for undoing a move. Perhaps it cannot be implemented because of
> conflicts across games, but it would be a wonderful feature addition!
> 

There is already a "z" shortcut for undoing (without the Ctrl) - for all games.
Is that good enough?

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
First stop for Perl beginners - http://perl-begin.org/

The cake was not a lie for Chuck Norris.
    — http://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by aguador** [comment]
Sholomi, Color me very red ... no, make that scarlet!  I have been using Spider for several years now, and never noticed that! As Gilda Radner used to say on SNL in the US: "Never mind!" (And my apologies.)

**Comment by shlomif** [comment]
Hi,

On Tue, 10 Apr 2018 12:18:06 +0000 (UTC)
aguador <notifications@github.com> wrote:

> Sholomi, Color me very red ... no, make that scarlet!  I have been using
> Spider for several years now, and never noticed that! As Gilda Radner used to
> say on SNL in the US: "Never mind!" (And my apologies.)
> 

see
https://www.amazon.com/Design-Everyday-Things-Donald-Norman/dp/0465067107?ie=UTF8&*Version*=1&*entries*=0 .
We may still wish to implement Ctrl+Z as an alternative keybinding because it
is the more standard one and to avoid such questions in the future. See
https://www.joelonsoftware.com/2007/02/19/seven-steps-to-remarkable-customer-service/ .

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
https://github.com/sindresorhus/awesome - curated list of lists

In Soviet Russia, cats own you. No, wait! Cats own you everywhere.

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Fixed in 3e595ae1832e32853e796fff35cf30c37a116108 , but we could revamp more keybindings.
