### ISSUE TITLE
Mint / Publish a new stable 2.2 Release - what needs to be done beforehand?

### ISSUE THREAD

**Issue by shlomif** [shlomif/PySolFC#72]
I want to publish a new stable release, in part because from my experience people do not adequately test the prereleases and because we now have a usable windows package (thanks @Programator2 !).

So what needs to be done?

We need a usable release announcement in reddit-compatible markdown - @jan-kleks - can you help?

Are there any show stopping bugs?

I suppose the Android / Kivy port does not have to block it and we can keep it py2-only for now - @lufebe16 - what do you think?

Anything else?

**Comment by jan-kleks** [comment]
@shlomif I will try to help. Do you want it to be a release for "normal" users or a bit more "power" users?

**Comment by jan-kleks** [comment]
A very preliminary version of the reddit/Hacker News announcement. Any suggestions are welcome, I’m trying to keep it short, so that people would not fall asleep…

Before making the announcement: 

Maybe we could set up a very, very simple website such as this one (created with https://pages.github.com): http://openhantek.org BTW, do we still need SourceForge? What about redirecting everything to GitHub to keep the development focused?

I guess we do not consider changing the name of the project yet as discussed here: https://github.com/shlomif/PySolFC/issues/13

As I mentioned many times before we could REALLY use at least one cardset which would be compatible with Full HD screens before “going vector”: https://github.com/shlomif/PySolFC/issues/50 We might even try resizing our very retro pixelated default PySolFC cardset for this (it shouldn’t look much worse…).


TITLE: PySolFC is back, new stable release! — open-source collection of +1000 solitaire card/mahjong games

PySolFC is a free and open-source collection of +1000 solitaire card and mahjong games with a great set of features and solver/analysis tools. The application is almost 20 years old [I will put this link here: http://solitaire.vegard2.net/pysol.html], and the current development efforts are focused in Shlomi Fish’s GitHub repo.

So, Shlomi Fish and other awesome contributors present to you, a new stable release (the last one was in distant 2009!) of PySolFC, new features:

[Fill in the features and improvements, shlomif, please]

And here you can find download links for current Windows, Linux, Android version [Err… I don’t think we have a new macOS version yet?, shlomif. Any other operating systems? Would it work on BSD?]

Future plans:

— vector-based fully scalable cards and graphics

[And what else shlomif?]

If you want to help, we need:

— developers

— graphic designers who would help with improving the app’s look

— people to help with documentation and translations

— people who would spread the word

We will gladly answer any questions!

Remember that apart from this thread you can also contact us using the FOSS Card Games group and a real time Internet chat on the ##pysol chat room on Freenode (note the double octothorpe/hash-sign/pound-sign).

**Comment by lufebe16** [comment]
On Tue, 10 Apr 2018 16:15:33 +0000 (UTC)
Shlomi Fish <notifications@github.com> wrote:

The kivy port is designed mainly to run on touch devices (currently
only android). It needs python2, as the apk is built with python2. On
the desktop it also runs with python3. (But this was not tested in deep 
details). There are no known issues.

Note on	cards:
A new release should also include a minimal choice of cardsets I think. 
As the version of 2009 did.

Note on python2:
Python2 seems to be still the default interpreter in linux distros
(Debian, Mint/Ubuntu, Centos). So python2 compatibility will need to be
kept on for a while.

> I want to publish a new stable release, in part because from my experience people do not adequately test the prereleases and because we now have a usable windows package (thanks @Programator2 !).
> 
> So what needs to be done?
> 
> We need a usable release announcement in reddit-compatible markdown - @jan-kleks - can you help?
> 
> Are there any show stopping bugs?
> 
> I suppose the Android / Kivy port does not have to block it and we can keep it py2-only for now - @lufebe16 - what do you think?
> 
> Anything else?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/shlomif/PySolFC/issues/72


--

**Comment by shlomif** [comment]
Hi!

On Wed, 11 Apr 2018 10:08:54 +0000 (UTC)
lufebe16 <notifications@github.com> wrote:

> On Tue, 10 Apr 2018 16:15:33 +0000 (UTC)
> Shlomi Fish <notifications@github.com> wrote:
> 
> The kivy port is designed mainly to run on touch devices (currently
> only android). It needs python2, as the apk is built with python2. On
> the desktop it also runs with python3. (But this was not tested in deep 
> details). There are no known issues.
> 

I see. Thanks a lot for that.

> Note on	cards:
> A new release should also include a minimal choice of cardsets I think. 
> As the version of 2009 did.
> 

The windows' binary release already contains a selection of cardsets. They
should not be hard to install on linux.

> Note on python2:
> Python2 seems to be still the default interpreter in linux distros
> (Debian, Mint/Ubuntu, Centos). So python2 compatibility will need to be
> kept on for a while.
> 

Sure, I am not planning to drop support for py2 any time soon.

> > I want to publish a new stable release, in part because from my experience
> > people do not adequately test the prereleases and because we now have a
> > usable windows package (thanks @Programator2 !).
> > 
> > So what needs to be done?
> > 
> > We need a usable release announcement in reddit-compatible markdown -
> > @jan-kleks - can you help?
> > 
> > Are there any show stopping bugs?
> > 
> > I suppose the Android / Kivy port does not have to block it and we can keep
> > it py2-only for now - @lufebe16 - what do you think?
> > 
> > Anything else?
> > 
> > -- 
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub:
> > https://github.com/shlomif/PySolFC/issues/72  
> 
> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/humour/ways_to_do_it.html

Selina: Quite a weird lot this supernatural underworld seems to be.
    — http://www.shlomifish.org/humour/Selina-Mandrake/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Hi Jan!

On Wed, 11 Apr 2018 01:42:48 +0000 (UTC)
Jan Kleks <notifications@github.com> wrote:

> A very preliminary version of the reddit/Hacker News announcement. Any
> suggestions are welcome, I’m trying to keep it short, so that people would
> not fall asleep…
> 
> Before making the announcement: 
> 
> Maybe we could set up a very, very simple website such as this one (created
> with https://pages.github.com): http://openhantek.org BTW, do we still need
> SourceForge? What about redirecting everything to GitHub to keep the
> development focused?
> 

see what I wrote here -
https://www.reddit.com/r/Python/comments/8237i3/help_is_needed_in_preparing_a_windows_binary/dv84xxu/ .
You can send revamps of the site here -
https://github.com/shlomif/pysolfc-website .

> I guess we do not consider changing the name of the project yet as discussed
> here: https://github.com/shlomif/PySolFC/issues/13
> 

not for now,

> As I mentioned many times before we could REALLY use at least one cardset
> which would be compatible with Full HD screens before “going vector”:
> https://github.com/shlomif/PySolFC/issues/50 We might even try resizing our
> very retro pixelated default PySolFC cardset for this (it shouldn’t look much
> worse…).
> 

We can also try rendering an existing SVG cardset into large PNGs using
the inkscape cmdline.

> 
> TITLE: PySolFC is back, new stable release! — open-source collection of +1000
> solitaire card/mahjong games
> 

This seems too informal.

> PySolFC is a free and open-source collection of +1000 solitaire card and

+1000 should be "over 1,000"

> mahjong games with a great set of features and solver/analysis tools. The
> application is almost 20 years old [I will put this link here:
> http://solitaire.vegard2.net/pysol.html], and the current development efforts
> are focused in Shlomi Fish’s GitHub repo.
> 

s/shlomi fish's/the /

> So, Shlomi Fish and other awesome contributors present to you, a new stable
> release (the last one was in distant 2009!) of PySolFC, new features:
> 

"The PySol FC developers are proud to present a new stable release of PySolFC.
Among the new features:"

> [Fill in the features and improvements, shlomif, please]
> 

see http://pysolfc.sourceforge.net/ . Some of them may be quite minor, though.
> And here you can find download links for current Windows, Linux, Android

s/And h/H/

> version [Err… I don’t think we have a new macOS version yet?, shlomif. Any
> other operating systems? Would it work on BSD?]

We don't have a macOS binary package yet, but the code should work there and
may be easy to install using
https://en.wikipedia.org/wiki/Homebrew_%28package_management_software%29 or
similar. Regarding the BSDs - it should work there but I didn't test
extensively. There may be bugs, but they will be fixed if reported.

> 
> Future plans:
> 
> — vector-based fully scalable cards and graphics
> 
> [And what else shlomif?]
> 

I don't have any other show stopping features I'd like to add - perhaps
handling the solvers better in the game creation wizard.


> If you want to help, we need:
> 
> — developers
> 
> — graphic designers who would help with improving the app’s look
> 
> — people to help with documentation and translations
> 
> — people who would spread the word
> 
> We will gladly answer any questions!
> 
> Remember that apart from this thread you can also contact us using the FOSS
> Card Games group and a real time Internet chat on the ##pysol chat room on
> Freenode (note the double octothorpe/hash-sign/pound-sign).
> 

make sure to add links for everything.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
First stop for Perl beginners - http://perl-begin.org/

<PerlJam> I’m trying to achieve world peace and this regex is the last thing
standing in my way! ;)

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by jan-kleks** [comment]
>see what I wrote here

Okay, I see. I suggested https://pages.github.com/ because I thought that maybe you would like to transfer everything to GitHub right now, and to have everything nicely integrated, but maybe this would take some time indeed... The point is, I wonder what links should we put in the announcement? Which should we present as the homepage? To the GitHub repo or to http://pysolfc.sourceforge.net? So that people wouldn't get confused...

>We can also try rendering an existing SVG cardset into large PNGs using
the inkscape cmdline.

That's another option. I think this cardset is the most "canonical" one: https://sourceforge.net/p/vector-cards/home/Vector_Poker_Playing_Cards_SVG/

>This seems too informal

But we should show our excitement somehow. ;) I will think how to rewrite this.

Sorry, but I'm not sure what these mean: "s/shlomi fish's/the /" "s/And h/H/"

>make sure to add links for everything

Of course. I won't post anything without your consent.

**Comment by shlomif** [comment]
Hi Jan,

On Thu, 12 Apr 2018 15:51:18 -0700
Jan Kleks <notifications@github.com> wrote:

> >see what I wrote here  
> 
> Okay, I see. I suggested https://pages.github.com/ because I thought that
> maybe you would like to transfer everything to GitHub right now, and to have
> everything nicely integrated, but maybe this would take some time indeed...

GitHub is not the silver bullet -
https://en.wikipedia.org/wiki/No_Silver_Bullet . GH pages won't make us better
integrated than the SF website.

> The point is, I wonder what links should we put in the announcement? Which
> should we present as the homepage? To the GitHub repo or to
> http://pysolfc.sourceforge.net? So that people wouldn't get confused...
> 

To http://pysolfc.sourceforge.net/ .

> >We can also try rendering an existing SVG cardset into large PNGs using  
> the inkscape cmdline.
> 
> That's another option. I think this cardset is the most "canonical" one:
> https://sourceforge.net/p/vector-cards/home/Vector_Poker_Playing_Cards_SVG/
> 

OK.

> >This seems too informal  
> 
> But we should show our excitement somehow. ;) I will think how to rewrite
> this.
> 
> Sorry, but I'm not sure what these mean: "s/shlomi fish's/the /" "s/And h/H/"
> 

see
https://www.gnu.org/software/sed/manual/html_node/The-_0022s_0022-Command.html
and http://www.catb.org/jargon/html/writing-style.html .

> >make sure to add links for everything  
> 
> Of course. I won't post anything without your consent.
> 

I mean link to our resources from within the text.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Interview with Ben Collins-Sussman - http://shlom.in/sussman

The apple completely supplanted the tree.
    — http://www.shlomifish.org/humour/Summerschool-at-the-NSA/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Just a note that I started revamping @jan-kleks 's version here - https://github.com/shlomif/pysolfc-announcements .

**Comment by jan-kleks** [comment]
@shlomif Looking good to me. Maybe we should mentioned there that "source" basically means Linux (and that it could possibly be compiled for other operating systems). Also, it might be a good idea to explain the SourceForge/GitHub situation at the end of the announcement, people will start asking questions why is that...

I will look again at what subreddits we can post this.

**Comment by shlomif** [comment]
@jan-kleks : do you agree to relicense the original version of the announcement under the https://duckduckgo.com/?q=expat+license&ia=web ? This will help a lot.

**Comment by jan-kleks** [comment]
@shlomif 

>do you agree to relicense the original version of the announcement under the https://duckduckgo.com/?q=expat+license&ia=web ? This will help a lot.

Yes, of course.

Okay, so for the time being I think these subreddits (and Hacker News) will be good for making the announcement:

https://www.reddit.com/r/opensourcegames/

https://www.reddit.com/r/Python/

https://www.reddit.com/r/opensource/

https://www.reddit.com/r/linux_gaming/

https://www.reddit.com/r/linux/

These subreddits are frequented by people who might still remember (use) PySolFC, and who care about open-source software. Of course, you should make the announcement from your reddit/Hacker News account shlomif, so that you get new comments notifications, and you would be able to reply to the questions quickly.

In the future, when hopefully we will have means to improve the app's look, so that it would look less '90s/early '00s and 2018, we can start making the announcements at mainstream gaming subreddits. Unfortunately, as most users judge a book by its cover, a casual gamer instead of seeing PySolFC's awesome set of solitaire features, would only focus on its outdated look (just believe me, I'm really into both retro and modern gaming). So these mainstream subreddits have to wait for now IMHO, I'm afraid...  

When @lufebe16 will be ready, we can also make the announcement at https://www.reddit.com/r/Android/ at some point. BTW, maybe it would be a good idea to add a screenshot/-s for the Android version to PySolFC webpages?

**Comment by shlomif** [comment]
On Sat, 14 Apr 2018 23:08:23 +0000 (UTC)
Jan Kleks <notifications@github.com> wrote:

> @shlomif Looking good to me. Maybe we should mentioned there that "source"
> basically means Linux (and that it could possibly be compiled for other
> operating systems). Also, it might be a good idea to explain the
> SourceForge/GitHub situation at the end of the announcement, people will
> start asking questions why is that...
> 

done and done, thanks!

> I will look again at what subreddits we can post this.
> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Summer Glau Facts - http://shlom.in/sglau-facts

Summer Glau does not have to hurt you if she doesn't want to . Chuck Norris
kills everyone in sight.
    — http://www.shlomifish.org/humour/bits/facts/Summer-Glau/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Hi,

On Sun, 15 Apr 2018 21:55:27 +0000 (UTC)
Jan Kleks <notifications@github.com> wrote:

> @shlomif 
> 
> >do you agree to relicense the original version of the announcement under the
> >https://duckduckgo.com/?q=expat+license&ia=web ? This will help a lot.  
> 
> Yes, of course.
> 

thanks!

> Okay, so for the time being I think these subreddits (and Hacker News) will
> be good for making the announcement:
> 
> https://www.reddit.com/r/opensourcegames/
> 
> https://www.reddit.com/r/Python/
> 
> https://www.reddit.com/r/opensource/
> 
> https://www.reddit.com/r/linux_gaming/
> 
> https://www.reddit.com/r/linux/
> 
> These subreddits are frequented by people who might still remember (use)
> PySolFC, and who care about open-source software. Of course, you should make
> the announcement from your reddit/Hacker News account shlomif, so that you
> get new comments notifications, and you would be able to reply to the
> questions quickly.

OK.

> 
> In the future, when hopefully we will have means to improve the app's look,
> so that it would look less '90s/early '00s and 2018, we can start making the
> announcements at mainstream gaming subreddits. Unfortunately, as most users
> judge a book by its cover, a casual gamer instead of seeing PySolFC's awesome
> set of solitaire features, would only focus on its outdated look (just
> believe me, I'm really into both retro and modern gaming). So these
> mainstream subreddits have to wait for now IMHO, I'm afraid...  
> 

ah.

> When @lufebe16 will be ready, we can also make the announcement at
> https://www.reddit.com/r/Android/ at some point. BTW, maybe it would be a
> good idea to add a screenshot/-s for the Android version to PySolFC webpages?
> 

Sure!



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/humour/bits/New-versions-of-the-GPL/

A wiseman can learn from a fool much more than a fool can ever learn from a
wiseman.               — http://en.wikiquote.org/wiki/Cato_the_Elder

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Release tagged and uploaded and is being announced. Thanks all.
